name: Run Python Script

on:
  push:
    branches:
      - main  # Automatically run when changes are pushed to the main branch
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  execute-script:
    runs-on: ubuntu-latest  # Use a Linux runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Check out your repository code

      - name: Set Up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Set Python version

      - name: Install Required Packages
        run: |
          pip install pdfplumber pandas openpyxl  # Install dependencies

      - name: Run the Python Script
        run: |
          python WorkStudentTask.py  

      - name: Commit Output Files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add generated output files"
          git push
